BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUTO_SHIFT_ENABLE = no
TAP_DANCE_ENABLE = no

AUDIO_ENABLE = no # My next keyboard needs a speaker...

EXTRAKEY_ENABLE = yes
LEADER_ENABLE = yes
NKRO_ENABLE = yes

LAYOUTS = directional
